image: ubuntu:18.04

pipelines:
  default:
    - step:
        script:
          - apt-get update -y
          - apt-get install -y build-essential zlibc zlib1g-dev ruby ruby-dev openssl libxslt-dev libxml2-dev libssl-dev libreadline6-dev libyaml-dev libsqlite3-dev sqlite3
          - curl -Lo ./bosh https://s3.amazonaws.com/bosh-cli-artifacts/bosh-cli-5.0.1-linux-amd64
          - chmod +x ./bosh
          - mv ./bosh /usr/local/bin/bosh
          - bosh -v
          - mkdir -p ~/bosh-env/virtualbox
          - cd ~/bosh-env/virtualbox
          -  git clone https://github.com/cloudfoundry/bosh-deployment.git
          - export BOSH_LOG_LEVEL=debug
          - ./bosh-deployment/docker/create-env.sh
          - source .envrc
          - apt-get install -y git curl
          - git submodule update --init --recursive --force
          - bosh create release --name neo4j --force
          - bosh upload release
          - templates/make_manifest warden
          - bosh -n deploy